### ISSUE TITLE
ERROR: 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by rohitrsh** [StackStorm/showcase-ansible-chatops#13]
Hi,

I have installed latest st2 on centos 7 version 2.1.1, while installing st2-ansible-chatops pack I am getting below error.

Its working fine for me on RHEL-7 with st2 version 2.0.1

[root@chatops]# st2 run packs.install packs=st2-ansible-chatops repo_url=armab/st2-ansible-chatops
ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('repo_url' was unexpected) for url: http://127.0.0.1:9101/v1/executions

Please let me know, if there any configuration which i am missing.

-Rohit

**Comment by armab** [comment]
Yeah, for older st2 `2.0` the command is: 
```sh
st2 run packs.install packs=st2-chatops-aliases repo_url=armab/st2-chatops-aliases
```

For new and recent StackStorm `2.1` the syntax to install the pack (https://docs.stackstorm.com/packs.html#installing-a-pack) was changed:
```sh
st2 pack install https://github.com/armab/st2-chatops-aliases
```

since we introduced new Pack Management and StackStorm Exchange, see: https://stackstorm.com/2016/12/06/2-1-new-pack-management/

I've created Issue https://github.com/StackStorm/showcase-ansible-chatops/issues/14 to address it later and update all references with the new syntax.

Thanks for your report!
